### ISSUE TITLE
Politeness delay

### ISSUE THREAD

**Issue by dimiro1** [fanyang01/crawler#6]
There is any option to config the crawler to waits at least 200 (for example) milliseconds between requests?

**Comment by fanyang01** [comment]
The queue/ratelimitq package, which implements the `queue.WaitQueue` interface,  provides a host-based rate limiter. You can write something like this:

``` go
queue := ratelimitq.NewWaitQueue(&ratelimitq.Option{
    Limit: func(host string) time.Duration {
        return 200 * time.Millisecond
    },
})
crawler := crawler.New(&crawler.Config{ Queue: queue })
```

**Comment by dimiro1** [comment]
Thank you
